name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Or main, depending on your default branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Use your project's required Node.js version

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build  # Ensure this script generates your build in the 'dist' directory or adjust accordingly

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist  # Or your build output directory
